#!/bin/sh

status=$(nordvpn status | awk '/Status/ {print $2}')

if [ "$status" == "Connected" ]; then
    nordvpn d &>/dev/null
else
    notify-send "Connection to VPN..."
    nordvpn c sweden &>/dev/null
fi
