#!/bin/sh

status=$(nordvpn status | awk '/Status/ {print $2}')

if [ "$status" == "Connected" ]; then
    echo '%{F#388e3c}%{F-}   '
elif [ "$status" == "Disconnected" ]; then
    echo '   '
else
    echo '   '
fi
